## Input Configuration
generated:
  name: graphrag
  answer_base_path: input/graphrag/activity_cat1.json
assertions: # List of other conditions to compare against the base.
  assertions_path: input/activity_cat1_assertions.json # The path to the assertions file. Modify this based on your dataset.

pass_threshold: 0.5 # The threshold for passing the assertion. If the score is above this threshold, the assertion is considered passed.
trials: 4 # Number of trials to repeat the scoring process for each question-assertion pair.

## LLM Configuration
llm_config: 
  model: gpt-5-mini
  auth_type: api_key # or azure_managed_identity
  api_key: ${OPENAI_API_KEY} # remove this if using azure_managed_identity
  llm_provider: openai.chat # or azure.openai.chat | azure.inference.chat
  concurrent_requests: 4 # The number of concurrent requests to send to the model.
  # init_args:
  #   Additional initialization arguments for the LLM can be added here.
  #   For example, you can set the model version or other parameters.
  #   api_version: 2024-12-01-preview
  #   azure_endpoint: https://<instance>.openai.azure.com
  call_args:
  #   Additional arguments for the LLM call can be added here.
  #   For example, you can set the temperature, max tokens, etc.
    temperature: 1
  #   seed: 42
  # custom_providers: # When implementing a custom LLM provider, you can add it here.
  #   - model_type: chat
  #     name: custom.chat # This name should match the llm_provider above
  #     module: custom_test.custom_provider
  #     model_class: CustomChatModel

prompts_config:
  user_prompt:
    prompt: prompts/assertion_user_prompt.txt
  system_prompt:
    prompt: prompts/assertion_system_prompt.txt